### ISSUE TITLE
Unable to proceed on Linux Mint error

### ISSUE THREAD

**Issue by tastyhub** [portellam/Auto-vfio-pci#57]
I'd like to give your script a try as i've been unsuccessful stubbing out my gpu. I have 2 AMD gpus, RX 570 and 5700XT. 

Running Linux Mint 21.3 x86_64, kernel 6.5.0-44-generic

$ sudo bash deploy-vfio --ignore-distro
deploy-vfio: An error occurred: System distribution 'linuxmint' is not explicitly supported.
deploy-vfio: An error occurred: System is not supported.

**Comment by portellam** [comment]
What a pleasant surprise, thank you for trying out my script!

May I ask, did you pull down from the master branch?

Regarding your issue, I see that the logic to set the flag is never called.
For now, please uncomment the following line, found in `deploy-vfio.d/bin/args_common`:

```bash
# is_option_of_compatibility "$@" || return 1
```

change to...

```bash
is_option_of_compatibility "$@" || return 1
```

Please let me know of any issues.

I cannot guarantee 100% stability with this version of the script. I recommend using **Static** VFIO setup for now. The README and/or HELP may show commands which are not currently enabled.

I am in the process of doing a **major rewrite**. Unfortunately, I am one man and I have a lot of work lately. Assume it to be finished by EOY.

Thanks again for choosing my script. I was actually working on another related project, now about to head to bed.

**Comment by portellam** [comment]
Closing ticket after no response from user. Please let me know of any issues.
